---
- name: Verify
  hosts: mock_server
  connection: local
  tasks:
    - name: Check that the component request was sent to the mock controller exactly 4 times per docker instance (includes the idempotence test)
      uri:
        url: "https://{{ inventory_hostname }}:1080/mockserver/verify"
        method: PUT
        body:
          httpRequest:
            path: "/api/v1/services/environments/production/apps/www.example.com/components/root"
          times:
            atLeast: 4
            atMost: 4
        status_code: 202
        body_format: json
        headers:
          Content-Type: application/json
        validate_certs: false
